### ISSUE TITLE
Embed monad transformers

### ISSUE THREAD

**Issue by Fristi** [kailuowang/mainecoon#26]
When we have a `MonadTrans` type class we can add a `embed` method to `FunctorK`:

```
def embed[M[_], MT[_[_], _]](fa: F[M])(implicit D: MonadTrans[MT], M: Monad[M]): F[MT[M, ?]] = functorK.mapK(fa)(new (M ~> MT[M, ?]) {
      override def apply[A](fa: M[A]): MT[M, A] = D.lift(fa)
    })
```

Maybe it would be nice if we can define the natural transformation implicitly such that we can embed a `M[_]` into a complex monad transformer stack. Like `Future ~> EitherT[WriterT[Future, List[String], ?], String, ?]`.

**Comment by wedens** [comment]
I think it's more in scope of [cats-mtl](https://github.com/edmundnoble/cats-mtl).

**Comment by kubukoz** [comment]
Not sure if it's the same issue...

Imagine this: 
```scala
type Authentication = String
type AuthenticatedT[F[_], T] = ReaderT[F, Authentication, T]

@autoFunctorK(false)
trait MyService[F[_]] {
  def findResult(): AuthenticatedT[F, String]
}
```

The macro will expand, but the result will not typecheck - the generated `mapK` will look like:

```scala
def mapK[F[_], G[_]](af: MyService[F])(fk: _root_.cats.~>[F, G]): MyService[G] = new MyService[G] {
  def findResult(): AuthenticatedT[F, String] = af.findResult()
}
```

Which is not the proper implementation - the findResult() method should be implemented as:
```scala
def findResult(): AuthenticatedT[G, String] = af.findResult().mapK(fk)
```

I understand that we'd probably need a dependency on cats-mtl and require `AuthenticatedT` to have some typeclass instance (I'm not quite familiar with the details of cats-mtl typeclasses yet, though, so I don't know which one), or just a `mapK` method with the correct shape...

Is this in scope for mainecoon, @kailuowang?

Note: not all methods in MyService will return `AuthenticatedT[F, ?]` - some might just do `F[?]`

**Comment by kailuowang** [comment]
This could be in scope but would be pretty hard to implement. You might have to hand roll a `FunctorK` instance for this one. Essentially you have two different effect types `F[_]` in your algebra. I haven't tried that design before.
