### ISSUE TITLE
Add an ApplyK type class?

### ISSUE THREAD

**Issue by LukaJCB** [kailuowang/mainecoon#38]
I'd love to see a very simple `ApplyK` typeclass that'd let us use something like this:

```scala
def map2K[F[_], G[_], H[_]](af: A[F], ag: A[G])(f: Tuple2K[F, G, ?] ~> H): A[H]
```

And it should also be able to be derived fairly easily, right?

**Comment by kailuowang** [comment]
Is this also isomorphic to `CartesianK` (or `SemigroupalK`) + `FunctorK` ?

**Comment by LukaJCB** [comment]
Yes exactly :)

**Comment by kailuowang** [comment]
so we have at least 3 options to provide derivation here. 
Option 1, in `ApplyK` companion, we provide a method that derives an instance from `FunctorK` and `SemigroupalK` instances. Then users have to add both `@autoFunctorK` and `@autoSemigroupalK` to their algebra. 
Option 2, we provide a new `@autoApplyK` annotation and reuse the code from the `@autoFunctorK` and `@autoSemigroupalK`.

WDYT?

**Comment by LukaJCB** [comment]
I think I prefer Option 2, seems more consistent and also more convenient for the end user. I'd gladly contribute the typeclass + laws + docs, but I'm not sure if I can help with the macros. If you want I could create a PR that adds those things :)

**Comment by kailuowang** [comment]
@LukaJCB, it would be awesome if you could add the typeclass + laws + docs.
Actually, if you want you could even add the derivation method in the companion mentioned in Option 1 (should be just a couple of lines of code I think) so that you can start using it while waiting on the `@autoApplyK` macro.

**Comment by LukaJCB** [comment]
Will do, thanks! :)

**Comment by LukaJCB** [comment]
Btw for a use case, you can look here :) https://github.com/typelevel/typelevel.github.com/pull/220

**Comment by kailuowang** [comment]
Noice, another awesome one from you.
